import Header from "./header"
import Input from "./Input"
import { SmallInp } from "./Input"
import InfoCard from "./InfoCard"
import Footer  from "./Footer"
import ProfileHeader from "./ProfileHeader"
import SideMenu from "./sideBar"
import SearchBox from "./Search"
import Loading from "./Loading"
import Sender from "./Sender"
import Receiver from "./Receiver"
import AddSuper from "./AddSuperVisor"
import Supervisors from "./supList"
import Patients from "./patients"
import Map from "./Map"
export {Header, Input, SmallInp, InfoCard, Footer, ProfileHeader, SideMenu, SearchBox, Loading, Sender , Receiver, AddSuper, Supervisors, Patients, Map}
